### ISSUE TITLE
睡眠唤醒是否正常

### ISSUE THREAD

**Issue by cuiliang0302** [conversun/B760M_MORTAR_Hackintosh#1]
微星B760睡眠唤醒正常吗？需要加什么参数吗？

**Comment by conversun** [comment]
> 微星B760睡眠唤醒正常吗？需要加什么参数吗？

目前睡了一晚上没问题，而且不需要加补丁

**Comment by cuiliang0302** [comment]
我看先前的首发测评，13代B系列主板电压都给的很高，导致发热和功耗增加，现在微星b760还有这个问题吗

**Comment by conversun** [comment]
> 我看先前的首发测评，13代B系列主板电压都给的很高，导致发热和功耗增加，现在微星b760还有这个问题吗

仍然有这个问题，目前解决方案是K系使用104微码的BIOS然后降压，但这个13700F就没办法了，满载1.35v 250w

**Comment by conversun** [comment]
有一台会搭配13700KF，到时候试试

**Comment by cuiliang0302** [comment]
好的，期待老哥后续测试结果，让我抄抄作业。
顺带问一句，老哥是专门研究黑苹果的吗，我在远景论坛看到的帖子，打算下个月趁京东百亿补贴上一波车，如果到时候安装黑苹果有问题，可以有偿解决吗？

**Comment by conversun** [comment]
> 好的，期待老哥后续测试结果，让我抄抄作业。 顺带问一句，老哥是专门研究黑苹果的吗，我在远景论坛看到的帖子，打算下个月趁京东百亿补贴上一波车，如果到时候安装黑苹果有问题，可以有偿解决吗？

目前测试仅改BIOS无效, 降压或者改loadline都会降低性能, 应该是要搭配WIN的软件手动调整才管用, 所以对这方面有要求的还是上Z790吧, 比如铭瑄那个带5个M2的, 或者等下个月MSI的Z790M

**Comment by conversun** [comment]
> 好的，期待老哥后续测试结果，让我抄抄作业。 顺带问一句，老哥是专门研究黑苹果的吗，我在远景论坛看到的帖子，打算下个月趁京东百亿补贴上一波车，如果到时候安装黑苹果有问题，可以有偿解决吗？

我是自己用和给周围的人用, 所以装机比较多, 付费就免了, 有问题可以交流; 
重要的还是硬件选择, 选对了少走弯路, 按我实际经验, 主板想要稳定最好是MSI, 技嘉睡眠不稳, ASUS网卡毛病多, 其他如华擎等二线更不用多说
