### ISSUE TITLE
MSI B760M max plus wifi + i5 13490F + GTX1060

### ISSUE THREAD

**Issue by wuziwei** [conversun/B760M_MORTAR_Hackintosh#4]
MSI B760M max plus wifi + i5 13490F + GTX1060
请教一下我的主机配置可以直接用你这个EFI吗？

**Comment by conversun** [comment]
> MSI B760M max plus wifi + i5 13490F + GTX1060 请教一下我的主机配置可以直接用你这个EFI吗？

不可以，需要换个显卡，比如RX580, RX6600

**Comment by bathIncense** [comment]
你好，
电脑型号  铭瑄 MS-B760M GAMING WIFI D5
操作系统  Microsoft Windows 10 专业工作站版 (64位)
CPU  (英特尔)13th Gen Intel(R) Core(TM) i5-13490F(2500 MHz)
主板  铭瑄 MS-B760M GAMING WIFI D5
内存  16.00 GB (   4800 MHz)
显卡  RX6600
网卡  Realtek PCIe 2.5GbE Family Controller
	网卡名称  Intel(R) Wi-Fi 6 AX101
	网卡厂商  英特尔
	Mac地址  30:89:4A:DA:6C:0E
这个配置可以使用吗？
